schema_version = "1.0.0"

id = "explodium"
version = "1.0.2"
name = "Explodium"
tagline = "Shows an exploded view of your mesh"
maintainer = "Shawn Shipley <shawn.shipley@gmail.com>"
type = "add-on"

website = "https://github.com/shawnshipley/explodium"

tags = ["Mesh", "Modeling"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Shawn Shipley",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/images",
  "/build",
  "/output",
  ".gitignore",
  "/Releases",
]
